name: CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        erl: [22, 23, 24]

    container:
      image: erlang:${{ matrix.erl }}

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: rebar3 eunit
    - name: Run dialyzer
      run: rebar3 dialyzer
    - name: Build formatter
      run: rebar3 as release escriptize
    - name: Run formatting check
      run: ./_build/release/bin/tqformat --verify "{src,test}/*.{hrl,erl,app.src}" "rebar.config"
